# Note: there are many handy hints in comments in this example -- remove them when you've finalized your recipe

# Jinja variables help maintain the recipe as you'll update the version only here.
# Using the name variable with the URL in line 14 is convenient
# when copying and pasting from another recipe, but not really needed.
{% set name = "cylc" %}
{% set version = "8.0rc1" %}


package:
  name: cylc
  version: {{ version }}

build:
  number: 0
  # Skip as Cylc requires Linux
  skip: True  # [py<37 or not linux]

# Note: to pin build numbers, if necessary, e.g.:
#    - cylc-flow {{ version }} *_3
requirements:
  host:
    - python
  run:
    - python
    - 'configurable-http-proxy >=4.1'
    - cylc-flow =={{ version }}
    - cylc-uiserver ==1.0.0
    - cylc-ui ==1.0.0

test:
  imports:
    - cylc.flow
    - cylc.uiserver
  commands:
    - cylc --version
    - cylc uiserver --help
    - configurable-http-proxy -V

about:
  home: https://cylc.github.io
  license: GPL-3.0-only
  license_family: GPL3
  license_file: 'COPYING'
  summary: A workflow engine for cycling systems
  description: |
    Cylc is a general purpose workflow engine that orchestrates cycling
    workflows very efficiently. It was designed for production weather,
    climate, and environmental forecasting systems, but it is not specialized
    to those domains and is agnostic to the applications it manages.
  doc_url: https://cylc.github.io/cylc-doc/
  dev_url: https://github.com/cylc/

extra:
  recipe-maintainers:
    - hjoliver
    - kinow
    - oliver-sanders
